add_newline = false

format = """\
$time$cmd_duration\
[ï• $username](bold magenta) \
[ïˆ³ $hostname](bold cyan) \
[ğŸ“‚ $directory](bold green) \
$git_branch$git_status \
$character"""

[time]
disabled = false
format = "[$time](bold blue) "

[cmd_duration]
min_time = 0
format = "took [$duration](bold yellow) "

[username]
style_user = "bold magenta"
style_root = "bold red"
show_always = true
format = "$user"

[hostname]
style = "bold cyan"
ssh_only = false
format = "$hostname"

[directory]
style = "bold green"
truncation_length = 3
truncate_to_repo = false
read_only = " ğŸ”’"
format = "$path"

[git_branch]
style = "bold bright-red"
format = "î‚  [$branch]($style) "

[git_status]
format = "[$all_status$ahead_behind](bold bright-yellow) "
style = "bold bright-yellow"
disabled = false

[character]
success_symbol = "[â¯](bold bright-blue) "
error_symbol = "[â¯](bold red) "

